### ISSUE TITLE
How to use color variables 

### ISSUE THREAD

**Issue by HusJAW** [joe-dev-public/fac-agency-website#29]
the naming system i used is simple and is divided to two parts 
`:root {
  --white-100: white;
  --black-900: black;
  --blue-800: #2d2e40;
  --orange-500: #ff836d;
  --orange-600: #fe545d;
  --red-500: #ff0606;
}`
part one: is the name of the color 
part two: is a number that represents the shade/darkness and is between 100-900

I have taken the liberty to create codePen example on how to css variables:
https://codepen.io/Hussain256/pen/KKyKWMR?editors=0100

**Comment by joe-dev-public** [comment]
I think this issue could be moved to the relevant PR, or possibly somewhere else? e.g. Discussions or Wiki. (Then we can close the issue. :)

**Comment by kmj673** [comment]
I made the the naming system under the CSS-wiki, you can check it on the Wiki tab.
if you would like to close this issue, you can close it.

**Comment by HusJAW** [comment]
sorry I wasn't sure how or where to share it
