### ISSUE TITLE
Maybe remove link from main logo at top of page?

### ISSUE THREAD

**Issue by joe-dev-public** [joe-dev-public/fac-agency-website#57]
If it was a multi-page site, the link here would make sense. As we just have a single page, could the link be confusing from an accessibility perspective?

(I'm thinking in particular about using keyboard to tab through links on the page, or a screen reader reading out a link that isn't useful. Though it might be skipped, because it's not part of ``<nav>``.)

**Comment by HusJAW** [comment]
having a log linked to home page is part of UX every user expects it.

**Comment by kmj673** [comment]
I think all the logos in the website which is connected to the index.html home as in `<a href=#>` or `<a href="index.html">`  is good feature to have.

Normally when user wants to get back to the home page, user clicks logo.

**Comment by joe-dev-public** [comment]
Sounds good, I'll close this issue :)
