### ISSUE TITLE
In the navigation, the team is not directed to the section in the page

### ISSUE THREAD

**Issue by kmj673** [joe-dev-public/fac-agency-website#65]
### The team `<a>` is not directed to the our team section in the `<main>` 

possible solution

- Add the same name as the team in the <a> href attributes.
- Change the id of `<section>`

**Comment by joe-dev-public** [comment]
Completely my fault, sorry! I changed the id of the div, forgetting it would break navigation.

I'll update the navigation and PR shortly.
